### ISSUE TITLE
Votancion musica

### ISSUE THREAD

**Issue by Fluc-UwU** [faztcommunity/fazt-bot#21]
![image](https://user-images.githubusercontent.com/67983451/87166157-c8503400-c290-11ea-9d6e-8ecaff858d30.png)

**Comment by tati1206** [comment]
Puedes dar una explicación detallada de lo que ocurre?

**Comment by danielsolartech** [comment]
El "error" fue que Reiva quitó la reacción dándole a "Eliminar todas las reacciones"
