### ISSUE TITLE
Se salto una cancion

### ISSUE THREAD

**Issue by Fluc-UwU** [faztcommunity/fazt-bot#33]
![image](https://user-images.githubusercontent.com/67983451/87254066-86b4ba00-c445-11ea-980f-c068284fe541.png)
![image](https://user-images.githubusercontent.com/67983451/87254072-92a07c00-c445-11ea-8950-1eaf68f9f13b.png)

**Comment by rodrigojimenezdencker** [comment]
Se saltó la de `Lin Nas X - panini` (la cual ni mostró en el chat) y la de `MGMT - Kids` (la cual si mostró en el chat pero no se llegó a reproducir nunca). Ninguna de las 2 fueron eliminadas en ningún momento.
