### ISSUE TITLE
Se saltó 2 canciones seguidas más la que ya sonaba

### ISSUE THREAD

**Issue by rodrigojimenezdencker** [faztcommunity/fazt-bot#34]
![Screenshot_6](https://user-images.githubusercontent.com/50848700/87254495-6dcaf980-c483-11ea-8fb2-76cec65959b6.png)
Estábamos tan tranquilos escuchando una canción y a mitad más o menos de la canción se cortó y se salto 2 más de golpe y empezó a reproducirse la última que se ve en la imagen.

**Comment by EnzoDiazDev** [comment]
Cierro para continuar en el issue https://github.com/faztcommunity/fazt-bot/issues/33
