### ISSUE TITLE
No indica correctamente el nombre de usuario

### ISSUE THREAD

**Issue by rodrigojimenezdencker** [faztcommunity/fazt-bot#39]
Dice @invalid-user en lugar del nombre de usuario real.

![Screenshot_2020-07-19-12-06-00-100_com discord](https://user-images.githubusercontent.com/50848700/87872397-62faf200-c9b8-11ea-8422-7bb3d6d3ad0e.jpg)

**Comment by zd4y** [comment]
Es un problema de discord cuando no han cargado los usuarios o cuando estos se salieron del server. No hay solución más que poner tambien el username sin mencionar como ya está

**Comment by rodrigojimenezdencker** [comment]
Ninguno de esos 2 usuarios había salido del server 😛 , pero parece que fue un error puntual porque ya no ocurre.
